# Generated by Django 5.1 on 2024-08-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='carwash.attendant')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.customer')),
                ('car_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carsize')),
            ],
        ),
        migrations.CreateModel(
            name='EstimatedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.IntegerField()),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carwash.carsize')),
            ],
        ),
    ]
